
package com.secusociale.portail.service.soap.immatRepresentantationDiplomatique;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "IMMAT_REP_DIPLOPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMAT_REP_DIPLO")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMMATREPDIPLOPortType {


    /**
     *
     * @param body
     * @throws IMMATREPDIPLOFault
     */
    @WebMethod(operationName = "IMMAT_REP_DIPLO", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMAT_REP_DIPLO")
    public void immatREPDIPLO(
        @WebParam(name = "IMMAT_REP_DIPLO", targetNamespace = "http://oracle.com/IMMAT_REP_DIPLO.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<IMMATREPDIPLO> body)
        throws IMMATREPDIPLOFault;

}
