
package com.secusociale.portail.service.soap.immatRepresentantationDiplomatique;

import com.secusociale.portail.service.PortailConstant;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * IMMAT_REP_DIPLO version 6: Inbound Webservice for Representation Diplomatique
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "IMMAT_REP_DIPLOService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMAT_REP_DIPLO", wsdlLocation = PortailConstant.REP_DIP_WSDL)
public class IMMATREPDIPLOService
    extends Service
{

    private final static URL IMMATREPDIPLOSERVICE_WSDL_LOCATION;
    private final static WebServiceException IMMATREPDIPLOSERVICE_EXCEPTION;
    private final static QName IMMATREPDIPLOSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMAT_REP_DIPLO", "IMMAT_REP_DIPLOService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.REP_DIP_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IMMATREPDIPLOSERVICE_WSDL_LOCATION = url;
        IMMATREPDIPLOSERVICE_EXCEPTION = e;
    }

    public IMMATREPDIPLOService() {
        super(__getWsdlLocation(), IMMATREPDIPLOSERVICE_QNAME);
    }

    public IMMATREPDIPLOService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IMMATREPDIPLOSERVICE_QNAME, features);
    }

    public IMMATREPDIPLOService(URL wsdlLocation) {
        super(wsdlLocation, IMMATREPDIPLOSERVICE_QNAME);
    }

    public IMMATREPDIPLOService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IMMATREPDIPLOSERVICE_QNAME, features);
    }

    public IMMATREPDIPLOService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IMMATREPDIPLOService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns IMMATREPDIPLOPortType
     */
    @WebEndpoint(name = "IMMAT_REP_DIPLOPort")
    public IMMATREPDIPLOPortType getIMMATREPDIPLOPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMAT_REP_DIPLO", "IMMAT_REP_DIPLOPort"), IMMATREPDIPLOPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IMMATREPDIPLOPortType
     */
    @WebEndpoint(name = "IMMAT_REP_DIPLOPort")
    public IMMATREPDIPLOPortType getIMMATREPDIPLOPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMAT_REP_DIPLO", "IMMAT_REP_DIPLOPort"), IMMATREPDIPLOPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (IMMATREPDIPLOSERVICE_EXCEPTION!= null) {
            throw IMMATREPDIPLOSERVICE_EXCEPTION;
        }
        return IMMATREPDIPLOSERVICE_WSDL_LOCATION;
    }

}
