
package com.secusociale.portail.service.soap.cessation_suspension;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM-ADD_CESSATION_OR_SUSPENSION version 2: Ajouter le processus de cessation ou de suspension d'activte
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM-ADD_CESSATION_OR_SUSPENSIONService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-ADD_CESSATION_OR_SUSPENSION", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-ADD_CESSATION_OR_SUSPENSION?WSDL")
public class CMADDCESSATIONORSUSPENSIONService
    extends Service {

    private final static URL CMADDCESSATIONORSUSPENSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMADDCESSATIONORSUSPENSIONSERVICE_EXCEPTION;
    private final static QName CMADDCESSATIONORSUSPENSIONSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-ADD_CESSATION_OR_SUSPENSION", "CM-ADD_CESSATION_OR_SUSPENSIONService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-ADD_CESSATION_OR_SUSPENSION?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMADDCESSATIONORSUSPENSIONSERVICE_WSDL_LOCATION = url;
        CMADDCESSATIONORSUSPENSIONSERVICE_EXCEPTION = e;
    }

    public CMADDCESSATIONORSUSPENSIONService() {
        super(__getWsdlLocation(), CMADDCESSATIONORSUSPENSIONSERVICE_QNAME);
    }

    public CMADDCESSATIONORSUSPENSIONService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMADDCESSATIONORSUSPENSIONSERVICE_QNAME, features);
    }

    public CMADDCESSATIONORSUSPENSIONService(URL wsdlLocation) {
        super(wsdlLocation, CMADDCESSATIONORSUSPENSIONSERVICE_QNAME);
    }

    public CMADDCESSATIONORSUSPENSIONService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMADDCESSATIONORSUSPENSIONSERVICE_QNAME, features);
    }

    public CMADDCESSATIONORSUSPENSIONService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMADDCESSATIONORSUSPENSIONService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMADDCESSATIONORSUSPENSIONSERVICE_EXCEPTION != null) {
            throw CMADDCESSATIONORSUSPENSIONSERVICE_EXCEPTION;
        }
        return CMADDCESSATIONORSUSPENSIONSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMADDCESSATIONORSUSPENSIONPortType
     */
    @WebEndpoint(name = "CM-ADD_CESSATION_OR_SUSPENSIONPort")
    public CMADDCESSATIONORSUSPENSIONPortType getCMADDCESSATIONORSUSPENSIONPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-ADD_CESSATION_OR_SUSPENSION", "CM-ADD_CESSATION_OR_SUSPENSIONPort"), CMADDCESSATIONORSUSPENSIONPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMADDCESSATIONORSUSPENSIONPortType
     */
    @WebEndpoint(name = "CM-ADD_CESSATION_OR_SUSPENSIONPort")
    public CMADDCESSATIONORSUSPENSIONPortType getCMADDCESSATIONORSUSPENSIONPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-ADD_CESSATION_OR_SUSPENSION", "CM-ADD_CESSATION_OR_SUSPENSIONPort"), CMADDCESSATIONORSUSPENSIONPortType.class, features);
    }

}
