
package com.secusociale.portail.service.soap.cessation_suspension;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CM-ADD_CESSATION_OR_SUSPENSIONPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-ADD_CESSATION_OR_SUSPENSION")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMADDCESSATIONORSUSPENSIONPortType {


    /**
     * @param body
     * @throws CMADDCESSATIONORSUSPENSIONFault
     */
    @WebMethod(operationName = "CM-ADD_CESSATION_OR_SUSPENSION", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-ADD_CESSATION_OR_SUSPENSION")
    public void cmADDCESSATIONORSUSPENSION(
        @WebParam(name = "CM-ADD_CESSATION_OR_SUSPENSION", targetNamespace = "http://oracle.com/CM-ADD_CESSATION_OR_SUSPENSION.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CMADDCESSATIONORSUSPENSION> body)
        throws CMADDCESSATIONORSUSPENSIONFault
    ;

}
