
package com.secusociale.portail.service.soap.employeurExistant;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CM_GET_EMPLOYEUR_DETAILSPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_EMPLOYEUR_DETAILS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGETEMPLOYEURDETAILSPortType {


    /**
     * 
     * @param body
     * @throws CMGETEMPLOYEURDETAILSFault
     */
    @WebMethod(operationName = "CM_GET_EMPLOYEUR_DETAILS", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_EMPLOYEUR_DETAILS")
    public void cmGETEMPLOYEURDETAILS(
        @WebParam(name = "CM_GET_EMPLOYEUR_DETAILS", targetNamespace = "http://oracle.com/CM_GET_EMPLOYEUR_DETAILS.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CMGETEMPLOYEURDETAILS> body)
        throws CMGETEMPLOYEURDETAILSFault
    ;

}
