
package com.secusociale.portail.service.soap.numeroCompteEmployeur;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM-PerAccountById version 2: Get Person Account by Id
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM-PerAccountByIdService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PerAccountById", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-PerAccountById?WSDL")
public class CMPerAccountByIdService
    extends Service {

    private final static URL CMPERACCOUNTBYIDSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMPERACCOUNTBYIDSERVICE_EXCEPTION;
    private final static QName CMPERACCOUNTBYIDSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PerAccountById", "CM-PerAccountByIdService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-PerAccountById?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMPERACCOUNTBYIDSERVICE_WSDL_LOCATION = url;
        CMPERACCOUNTBYIDSERVICE_EXCEPTION = e;
    }

    public CMPerAccountByIdService() {
        super(__getWsdlLocation(), CMPERACCOUNTBYIDSERVICE_QNAME);
    }

    public CMPerAccountByIdService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMPERACCOUNTBYIDSERVICE_QNAME, features);
    }

    public CMPerAccountByIdService(URL wsdlLocation) {
        super(wsdlLocation, CMPERACCOUNTBYIDSERVICE_QNAME);
    }

    public CMPerAccountByIdService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMPERACCOUNTBYIDSERVICE_QNAME, features);
    }

    public CMPerAccountByIdService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMPerAccountByIdService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMPERACCOUNTBYIDSERVICE_EXCEPTION != null) {
            throw CMPERACCOUNTBYIDSERVICE_EXCEPTION;
        }
        return CMPERACCOUNTBYIDSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMPerAccountByIdPortType
     */
    @WebEndpoint(name = "CM-PerAccountByIdPort")
    public CMPerAccountByIdPortType getCMPerAccountByIdPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PerAccountById", "CM-PerAccountByIdPort"), CMPerAccountByIdPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMPerAccountByIdPortType
     */
    @WebEndpoint(name = "CM-PerAccountByIdPort")
    public CMPerAccountByIdPortType getCMPerAccountByIdPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PerAccountById", "CM-PerAccountByIdPort"), CMPerAccountByIdPortType.class, features);
    }

}
