
package com.secusociale.portail.service.soap.remise_gracieuse_notification_url;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CM-GET_URL_NOTIFICATIONPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_URL_NOTIFICATION")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGETURLNOTIFICATIONPortType {


    /**
     * @param body
     * @throws CMGETURLNOTIFICATIONFault
     */
    @WebMethod(operationName = "CM-GET_URL_NOTIFICATION", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_URL_NOTIFICATION")
    public void cmGETURLNOTIFICATION(
        @WebParam(name = "CM-GET_URL_NOTIFICATION", targetNamespace = "http://oracle.com/CM-GET_URL_NOTIFICATION.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CMGETURLNOTIFICATION> body)
        throws CMGETURLNOTIFICATIONFault
    ;

}
