
package com.secusociale.portail.service.soap.remise_gracieuse_notification_url;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM-GET_URL_NOTIFICATION version 2: Recuperer l'accuse de reception remise gracieuse
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM-GET_URL_NOTIFICATIONService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_URL_NOTIFICATION", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-GET_URL_NOTIFICATION?WSDL")
public class CMGETURLNOTIFICATIONService
    extends Service {

    private final static URL CMGETURLNOTIFICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETURLNOTIFICATIONSERVICE_EXCEPTION;
    private final static QName CMGETURLNOTIFICATIONSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_URL_NOTIFICATION", "CM-GET_URL_NOTIFICATIONService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-GET_URL_NOTIFICATION?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETURLNOTIFICATIONSERVICE_WSDL_LOCATION = url;
        CMGETURLNOTIFICATIONSERVICE_EXCEPTION = e;
    }

    public CMGETURLNOTIFICATIONService() {
        super(__getWsdlLocation(), CMGETURLNOTIFICATIONSERVICE_QNAME);
    }

    public CMGETURLNOTIFICATIONService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETURLNOTIFICATIONSERVICE_QNAME, features);
    }

    public CMGETURLNOTIFICATIONService(URL wsdlLocation) {
        super(wsdlLocation, CMGETURLNOTIFICATIONSERVICE_QNAME);
    }

    public CMGETURLNOTIFICATIONService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETURLNOTIFICATIONSERVICE_QNAME, features);
    }

    public CMGETURLNOTIFICATIONService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETURLNOTIFICATIONService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETURLNOTIFICATIONSERVICE_EXCEPTION != null) {
            throw CMGETURLNOTIFICATIONSERVICE_EXCEPTION;
        }
        return CMGETURLNOTIFICATIONSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMGETURLNOTIFICATIONPortType
     */
    @WebEndpoint(name = "CM-GET_URL_NOTIFICATIONPort")
    public CMGETURLNOTIFICATIONPortType getCMGETURLNOTIFICATIONPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_URL_NOTIFICATION", "CM-GET_URL_NOTIFICATIONPort"), CMGETURLNOTIFICATIONPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMGETURLNOTIFICATIONPortType
     */
    @WebEndpoint(name = "CM-GET_URL_NOTIFICATIONPort")
    public CMGETURLNOTIFICATIONPortType getCMGETURLNOTIFICATIONPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GET_URL_NOTIFICATION", "CM-GET_URL_NOTIFICATIONPort"), CMGETURLNOTIFICATIONPortType.class, features);
    }

}
