
package com.secusociale.portail.service.soap.statutAttestationRegularite;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM-GetStatusDemandeAttestation version 2: get status demande attestation
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CM-GetStatusDemandeAttestationService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusDemandeAttestation", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-GetStatusDemandeAttestation?WSDL")
public class CMGetStatusDemandeAttestationService
    extends Service
{

    private final static URL CMGETSTATUSDEMANDEATTESTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETSTATUSDEMANDEATTESTATIONSERVICE_EXCEPTION;
    private final static QName CMGETSTATUSDEMANDEATTESTATIONSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusDemandeAttestation", "CM-GetStatusDemandeAttestationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-GetStatusDemandeAttestation?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETSTATUSDEMANDEATTESTATIONSERVICE_WSDL_LOCATION = url;
        CMGETSTATUSDEMANDEATTESTATIONSERVICE_EXCEPTION = e;
    }

    public CMGetStatusDemandeAttestationService() {
        super(__getWsdlLocation(), CMGETSTATUSDEMANDEATTESTATIONSERVICE_QNAME);
    }

    public CMGetStatusDemandeAttestationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETSTATUSDEMANDEATTESTATIONSERVICE_QNAME, features);
    }

    public CMGetStatusDemandeAttestationService(URL wsdlLocation) {
        super(wsdlLocation, CMGETSTATUSDEMANDEATTESTATIONSERVICE_QNAME);
    }

    public CMGetStatusDemandeAttestationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETSTATUSDEMANDEATTESTATIONSERVICE_QNAME, features);
    }

    public CMGetStatusDemandeAttestationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGetStatusDemandeAttestationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CMGetStatusDemandeAttestationPortType
     */
    @WebEndpoint(name = "CM-GetStatusDemandeAttestationPort")
    public CMGetStatusDemandeAttestationPortType getCMGetStatusDemandeAttestationPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusDemandeAttestation", "CM-GetStatusDemandeAttestationPort"), CMGetStatusDemandeAttestationPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGetStatusDemandeAttestationPortType
     */
    @WebEndpoint(name = "CM-GetStatusDemandeAttestationPort")
    public CMGetStatusDemandeAttestationPortType getCMGetStatusDemandeAttestationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusDemandeAttestation", "CM-GetStatusDemandeAttestationPort"), CMGetStatusDemandeAttestationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETSTATUSDEMANDEATTESTATIONSERVICE_EXCEPTION!= null) {
            throw CMGETSTATUSDEMANDEATTESTATIONSERVICE_EXCEPTION;
        }
        return CMGETSTATUSDEMANDEATTESTATIONSERVICE_WSDL_LOCATION;
    }

}
