
package com.secusociale.portail.service.soap.statutAttestationRegularite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CM-GetStatusDemandeAttestationPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusDemandeAttestation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGetStatusDemandeAttestationPortType {


    /**
     * 
     * @param body
     * @throws CMGetStatusDemandeAttestationFault
     */
    @WebMethod(operationName = "CM-GetStatusDemandeAttestation", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusDemandeAttestation")
    public void cmGetStatusDemandeAttestation(
        @WebParam(name = "CM-GetStatusDemandeAttestation", targetNamespace = "http://oracle.com/CM-GetStatusDemandeAttestation.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CMGetStatusDemandeAttestation> body)
        throws CMGetStatusDemandeAttestationFault
    ;

}
