
package com.secusociale.portail.service.soap.checkExistenceEmployeur;

import com.secusociale.portail.service.PortailConstant;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CmCheckExistenceEmployeur version 2: Check Taxpayer Existence
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CmCheckExistenceEmployeurService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmCheckExistenceEmployeur", wsdlLocation =   PortailConstant.CHECK_EXISTENCE_EMPLOYEUR_WSDL)
public class CmCheckExistenceEmployeurService
    extends Service
{

    private final static URL CMCHECKEXISTENCEEMPLOYEURSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMCHECKEXISTENCEEMPLOYEURSERVICE_EXCEPTION;
    private final static QName CMCHECKEXISTENCEEMPLOYEURSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmCheckExistenceEmployeur", "CmCheckExistenceEmployeurService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.CHECK_EXISTENCE_EMPLOYEUR_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMCHECKEXISTENCEEMPLOYEURSERVICE_WSDL_LOCATION = url;
        CMCHECKEXISTENCEEMPLOYEURSERVICE_EXCEPTION = e;
    }

    public CmCheckExistenceEmployeurService() {
        super(__getWsdlLocation(), CMCHECKEXISTENCEEMPLOYEURSERVICE_QNAME);
    }

    public CmCheckExistenceEmployeurService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMCHECKEXISTENCEEMPLOYEURSERVICE_QNAME, features);
    }

    public CmCheckExistenceEmployeurService(URL wsdlLocation) {
        super(wsdlLocation, CMCHECKEXISTENCEEMPLOYEURSERVICE_QNAME);
    }

    public CmCheckExistenceEmployeurService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMCHECKEXISTENCEEMPLOYEURSERVICE_QNAME, features);
    }

    public CmCheckExistenceEmployeurService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmCheckExistenceEmployeurService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CmCheckExistenceEmployeurPortType
     */
    @WebEndpoint(name = "CmCheckExistenceEmployeurPort")
    public CmCheckExistenceEmployeurPortType getCmCheckExistenceEmployeurPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmCheckExistenceEmployeur", "CmCheckExistenceEmployeurPort"), CmCheckExistenceEmployeurPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmCheckExistenceEmployeurPortType
     */
    @WebEndpoint(name = "CmCheckExistenceEmployeurPort")
    public CmCheckExistenceEmployeurPortType getCmCheckExistenceEmployeurPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmCheckExistenceEmployeur", "CmCheckExistenceEmployeurPort"), CmCheckExistenceEmployeurPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMCHECKEXISTENCEEMPLOYEURSERVICE_EXCEPTION!= null) {
            throw CMCHECKEXISTENCEEMPLOYEURSERVICE_EXCEPTION;
        }
        return CMCHECKEXISTENCEEMPLOYEURSERVICE_WSDL_LOCATION;
    }

}
