
package com.secusociale.portail.service.soap.cotisationParAnne;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CmRecupererInfosCotisationParAnneePortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmRecupererInfosCotisationParAnnee")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CmRecupererInfosCotisationParAnneePortType {


    /**
     * 
     * @param body
     * @throws CmRecupererInfosCotisationParAnneeFault
     */
    @WebMethod(operationName = "CmRecupererInfosCotisationParAnnee", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmRecupererInfosCotisationParAnnee")
    public void cmRecupererInfosCotisationParAnnee(
        @WebParam(name = "CmRecupererInfosCotisationParAnnee", targetNamespace = "http://oracle.com/CmRecupererInfosCotisationParAnnee.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CmRecupererInfosCotisationParAnnee> body)
        throws CmRecupererInfosCotisationParAnneeFault
    ;

}
