
package com.secusociale.portail.service.soap.derniersDeclarationsV2;

import com.secusociale.portail.config.Constants;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * DERN_DNS_EMPLOYEUR_SERVICE_V2 version 2: La liste des 10 derniéres DNS
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "DERN_DNS_EMPLOYEUR_SERVICE_V2Service", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE_V2", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE_V2?WSDL")
public class DERNDNSEMPLOYEURSERVICEV2Service
    extends Service
{

    private final static URL DERNDNSEMPLOYEURSERVICEV2SERVICE_WSDL_LOCATION;
    private final static WebServiceException DERNDNSEMPLOYEURSERVICEV2SERVICE_EXCEPTION;
    private final static QName DERNDNSEMPLOYEURSERVICEV2SERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE_V2", "DERN_DNS_EMPLOYEUR_SERVICE_V2Service");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE_V2?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DERNDNSEMPLOYEURSERVICEV2SERVICE_WSDL_LOCATION = url;
        DERNDNSEMPLOYEURSERVICEV2SERVICE_EXCEPTION = e;
    }

    public DERNDNSEMPLOYEURSERVICEV2Service() {
        super(__getWsdlLocation(), DERNDNSEMPLOYEURSERVICEV2SERVICE_QNAME);
    }

    public DERNDNSEMPLOYEURSERVICEV2Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DERNDNSEMPLOYEURSERVICEV2SERVICE_QNAME, features);
    }

    public DERNDNSEMPLOYEURSERVICEV2Service(URL wsdlLocation) {
        super(wsdlLocation, DERNDNSEMPLOYEURSERVICEV2SERVICE_QNAME);
    }

    public DERNDNSEMPLOYEURSERVICEV2Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DERNDNSEMPLOYEURSERVICEV2SERVICE_QNAME, features);
    }

    public DERNDNSEMPLOYEURSERVICEV2Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DERNDNSEMPLOYEURSERVICEV2Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns DERNDNSEMPLOYEURSERVICEV2PortType
     */
    @WebEndpoint(name = "DERN_DNS_EMPLOYEUR_SERVICE_V2Port")
    public DERNDNSEMPLOYEURSERVICEV2PortType getDERNDNSEMPLOYEURSERVICEV2Port() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE_V2", "DERN_DNS_EMPLOYEUR_SERVICE_V2Port"), DERNDNSEMPLOYEURSERVICEV2PortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DERNDNSEMPLOYEURSERVICEV2PortType
     */
    @WebEndpoint(name = "DERN_DNS_EMPLOYEUR_SERVICE_V2Port")
    public DERNDNSEMPLOYEURSERVICEV2PortType getDERNDNSEMPLOYEURSERVICEV2Port(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE_V2", "DERN_DNS_EMPLOYEUR_SERVICE_V2Port"), DERNDNSEMPLOYEURSERVICEV2PortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DERNDNSEMPLOYEURSERVICEV2SERVICE_EXCEPTION!= null) {
            throw DERNDNSEMPLOYEURSERVICEV2SERVICE_EXCEPTION;
        }
        return DERNDNSEMPLOYEURSERVICEV2SERVICE_WSDL_LOCATION;
    }

}
