
package com.secusociale.portail.service.soap.detailsCotisationParAnne;

import com.secusociale.portail.config.Constants;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CmRecupererInfosDetailsCotisation version 2: Recuperer les informations de cotisation par annee
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CmRecupererInfosDetailsCotisationService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmRecupererInfosDetailsCotisation", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmRecupererInfosDetailsCotisation?wsdl")
public class CmRecupererInfosDetailsCotisationService
    extends Service
{

    private final static URL CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_EXCEPTION;
    private final static QName CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmRecupererInfosDetailsCotisation", "CmRecupererInfosDetailsCotisationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmRecupererInfosDetailsCotisation?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_WSDL_LOCATION = url;
        CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_EXCEPTION = e;
    }

    public CmRecupererInfosDetailsCotisationService() {
        super(__getWsdlLocation(), CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_QNAME);
    }

    public CmRecupererInfosDetailsCotisationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_QNAME, features);
    }

    public CmRecupererInfosDetailsCotisationService(URL wsdlLocation) {
        super(wsdlLocation, CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_QNAME);
    }

    public CmRecupererInfosDetailsCotisationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_QNAME, features);
    }

    public CmRecupererInfosDetailsCotisationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmRecupererInfosDetailsCotisationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CmRecupererInfosDetailsCotisationPortType
     */
    @WebEndpoint(name = "CmRecupererInfosDetailsCotisationPort")
    public CmRecupererInfosDetailsCotisationPortType getCmRecupererInfosDetailsCotisationPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmRecupererInfosDetailsCotisation", "CmRecupererInfosDetailsCotisationPort"), CmRecupererInfosDetailsCotisationPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmRecupererInfosDetailsCotisationPortType
     */
    @WebEndpoint(name = "CmRecupererInfosDetailsCotisationPort")
    public CmRecupererInfosDetailsCotisationPortType getCmRecupererInfosDetailsCotisationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmRecupererInfosDetailsCotisation", "CmRecupererInfosDetailsCotisationPort"), CmRecupererInfosDetailsCotisationPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_EXCEPTION!= null) {
            throw CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_EXCEPTION;
        }
        return CMRECUPERERINFOSDETAILSCOTISATIONSERVICE_WSDL_LOCATION;
    }

}
