
package com.secusociale.portail.service.soap.detailsCotisationParAnne;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CmRecupererInfosDetailsCotisationPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmRecupererInfosDetailsCotisation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CmRecupererInfosDetailsCotisationPortType {


    /**
     * 
     * @param body
     * @throws CmRecupererInfosDetailsCotisationFault
     */
    @WebMethod(operationName = "CmRecupererInfosDetailsCotisation", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmRecupererInfosDetailsCotisation")
    public void cmRecupererInfosDetailsCotisation(
        @WebParam(name = "CmRecupererInfosDetailsCotisation", targetNamespace = "http://oracle.com/CmRecupererInfosDetailsCotisation.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CmRecupererInfosDetailsCotisation> body)
        throws CmRecupererInfosDetailsCotisationFault
    ;

}
