
package com.secusociale.portail.service.soap.statutDossierImmatriculation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Cm-GetStatusDossierImmatriculationPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/Cm-GetStatusDossierImmatriculation")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CmGetStatusDossierImmatriculationPortType {


    /**
     * 
     * @param body
     * @throws CmGetStatusDossierImmatriculationFault
     */
    @WebMethod(operationName = "Cm-GetStatusDossierImmatriculation", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/Cm-GetStatusDossierImmatriculation")
    public void cmGetStatusDossierImmatriculation(
        @WebParam(name = "Cm-GetStatusDossierImmatriculation", targetNamespace = "http://oracle.com/Cm-GetStatusDossierImmatriculation.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CmGetStatusDossierImmatriculation> body)
        throws CmGetStatusDossierImmatriculationFault
    ;

}
