
package com.secusociale.portail.service.soap.derniersDeclarations;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * DERN_DNS_EMPLOYEUR_SERVICE version 2: La liste des 10 derniéres paiements
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "DERN_DNS_EMPLOYEUR_SERVICEService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE?WSDL")
public class DERNDNSEMPLOYEURSERVICEService
    extends Service {

    private final static URL DERNDNSEMPLOYEURSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DERNDNSEMPLOYEURSERVICESERVICE_EXCEPTION;
    private final static QName DERNDNSEMPLOYEURSERVICESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE", "DERN_DNS_EMPLOYEUR_SERVICEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DERNDNSEMPLOYEURSERVICESERVICE_WSDL_LOCATION = url;
        DERNDNSEMPLOYEURSERVICESERVICE_EXCEPTION = e;
    }

    public DERNDNSEMPLOYEURSERVICEService() {
        super(__getWsdlLocation(), DERNDNSEMPLOYEURSERVICESERVICE_QNAME);
    }

    public DERNDNSEMPLOYEURSERVICEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DERNDNSEMPLOYEURSERVICESERVICE_QNAME, features);
    }

    public DERNDNSEMPLOYEURSERVICEService(URL wsdlLocation) {
        super(wsdlLocation, DERNDNSEMPLOYEURSERVICESERVICE_QNAME);
    }

    public DERNDNSEMPLOYEURSERVICEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DERNDNSEMPLOYEURSERVICESERVICE_QNAME, features);
    }

    public DERNDNSEMPLOYEURSERVICEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DERNDNSEMPLOYEURSERVICEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (DERNDNSEMPLOYEURSERVICESERVICE_EXCEPTION != null) {
            throw DERNDNSEMPLOYEURSERVICESERVICE_EXCEPTION;
        }
        return DERNDNSEMPLOYEURSERVICESERVICE_WSDL_LOCATION;
    }

    /**
     *
     * @return
     *     returns DERNDNSEMPLOYEURSERVICEPortType
     */
    @WebEndpoint(name = "DERN_DNS_EMPLOYEUR_SERVICEPort")
    public DERNDNSEMPLOYEURSERVICEPortType getDERNDNSEMPLOYEURSERVICEPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE", "DERN_DNS_EMPLOYEUR_SERVICEPort"), DERNDNSEMPLOYEURSERVICEPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DERNDNSEMPLOYEURSERVICEPortType
     */
    @WebEndpoint(name = "DERN_DNS_EMPLOYEUR_SERVICEPort")
    public DERNDNSEMPLOYEURSERVICEPortType getDERNDNSEMPLOYEURSERVICEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_DNS_EMPLOYEUR_SERVICE", "DERN_DNS_EMPLOYEUR_SERVICEPort"), DERNDNSEMPLOYEURSERVICEPortType.class, features);
    }

}
