
package com.secusociale.portail.service.soap.identifiantsEmployeurs;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * IDs_EMPLOYEUR_SERVICE version 2: Ids des employeurs
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "IDs_EMPLOYEUR_SERVICEService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IDs_EMPLOYEUR_SERVICE", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/IDs_EMPLOYEUR_SERVICE?WSDL")
public class IDsEMPLOYEURSERVICEService
    extends Service {

    private final static URL IDSEMPLOYEURSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException IDSEMPLOYEURSERVICESERVICE_EXCEPTION;
    private final static QName IDSEMPLOYEURSERVICESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IDs_EMPLOYEUR_SERVICE", "IDs_EMPLOYEUR_SERVICEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/IDs_EMPLOYEUR_SERVICE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        IDSEMPLOYEURSERVICESERVICE_WSDL_LOCATION = url;
        IDSEMPLOYEURSERVICESERVICE_EXCEPTION = e;
    }

    public IDsEMPLOYEURSERVICEService() {
        super(__getWsdlLocation(), IDSEMPLOYEURSERVICESERVICE_QNAME);
    }

    public IDsEMPLOYEURSERVICEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), IDSEMPLOYEURSERVICESERVICE_QNAME, features);
    }

    public IDsEMPLOYEURSERVICEService(URL wsdlLocation) {
        super(wsdlLocation, IDSEMPLOYEURSERVICESERVICE_QNAME);
    }

    public IDsEMPLOYEURSERVICEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, IDSEMPLOYEURSERVICESERVICE_QNAME, features);
    }

    public IDsEMPLOYEURSERVICEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public IDsEMPLOYEURSERVICEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (IDSEMPLOYEURSERVICESERVICE_EXCEPTION != null) {
            throw IDSEMPLOYEURSERVICESERVICE_EXCEPTION;
        }
        return IDSEMPLOYEURSERVICESERVICE_WSDL_LOCATION;
    }

    /**
     *
     * @return
     *     returns IDsEMPLOYEURSERVICEPortType
     */
    @WebEndpoint(name = "IDs_EMPLOYEUR_SERVICEPort")
    public IDsEMPLOYEURSERVICEPortType getIDsEMPLOYEURSERVICEPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IDs_EMPLOYEUR_SERVICE", "IDs_EMPLOYEUR_SERVICEPort"), IDsEMPLOYEURSERVICEPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDsEMPLOYEURSERVICEPortType
     */
    @WebEndpoint(name = "IDs_EMPLOYEUR_SERVICEPort")
    public IDsEMPLOYEURSERVICEPortType getIDsEMPLOYEURSERVICEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IDs_EMPLOYEUR_SERVICE", "IDs_EMPLOYEUR_SERVICEPort"), IDsEMPLOYEURSERVICEPortType.class, features);
    }

}
