
package com.secusociale.portail.service.soap.agencesRattachement;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * AGENCES_EMPLOYEUR_SERVICE version 2: Les agences de rattachement CSS et IPRES
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AGENCES_EMPLOYEUR_SERVICEService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/AGENCES_EMPLOYEUR_SERVICE", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/AGENCES_EMPLOYEUR_SERVICE?WSDL")
public class AGENCESEMPLOYEURSERVICEService
    extends Service {

    private final static URL AGENCESEMPLOYEURSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AGENCESEMPLOYEURSERVICESERVICE_EXCEPTION;
    private final static QName AGENCESEMPLOYEURSERVICESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/AGENCES_EMPLOYEUR_SERVICE", "AGENCES_EMPLOYEUR_SERVICEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/AGENCES_EMPLOYEUR_SERVICE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCESEMPLOYEURSERVICESERVICE_WSDL_LOCATION = url;
        AGENCESEMPLOYEURSERVICESERVICE_EXCEPTION = e;
    }

    public AGENCESEMPLOYEURSERVICEService() {
        super(__getWsdlLocation(), AGENCESEMPLOYEURSERVICESERVICE_QNAME);
    }

    public AGENCESEMPLOYEURSERVICEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCESEMPLOYEURSERVICESERVICE_QNAME, features);
    }

    public AGENCESEMPLOYEURSERVICEService(URL wsdlLocation) {
        super(wsdlLocation, AGENCESEMPLOYEURSERVICESERVICE_QNAME);
    }

    public AGENCESEMPLOYEURSERVICEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCESEMPLOYEURSERVICESERVICE_QNAME, features);
    }

    public AGENCESEMPLOYEURSERVICEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AGENCESEMPLOYEURSERVICEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCESEMPLOYEURSERVICESERVICE_EXCEPTION != null) {
            throw AGENCESEMPLOYEURSERVICESERVICE_EXCEPTION;
        }
        return AGENCESEMPLOYEURSERVICESERVICE_WSDL_LOCATION;
    }

    /**
     *
     * @return
     *     returns AGENCESEMPLOYEURSERVICEPortType
     */
    @WebEndpoint(name = "AGENCES_EMPLOYEUR_SERVICEPort")
    public AGENCESEMPLOYEURSERVICEPortType getAGENCESEMPLOYEURSERVICEPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/AGENCES_EMPLOYEUR_SERVICE", "AGENCES_EMPLOYEUR_SERVICEPort"), AGENCESEMPLOYEURSERVICEPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AGENCESEMPLOYEURSERVICEPortType
     */
    @WebEndpoint(name = "AGENCES_EMPLOYEUR_SERVICEPort")
    public AGENCESEMPLOYEURSERVICEPortType getAGENCESEMPLOYEURSERVICEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/AGENCES_EMPLOYEUR_SERVICE", "AGENCES_EMPLOYEUR_SERVICEPort"), AGENCESEMPLOYEURSERVICEPortType.class, features);
    }

}
