
package com.secusociale.portail.service.soap.cmdmt;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CmDmtPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmDmt")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CmDmtPortType {


    /**
     * 
     * @param body
     * @throws CmDmtFault
     */
    @WebMethod(operationName = "CmDmt", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmDmt")
    public void cmDmt(
        @WebParam(name = "CmDmt", targetNamespace = "http://oracle.com/CmDmt.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CmDmt> body)
        throws CmDmtFault
    ;

}
