
package com.secusociale.portail.service.soap.cmdmt;

import com.secusociale.portail.config.Constants;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CmDmt version 2: Mouvement des travailleurs
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CmDmtService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmDmt", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmDmt?WSDL")
public class CmDmtService
    extends Service
{

    private final static URL CMDMTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMDMTSERVICE_EXCEPTION;
    private final static QName CMDMTSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmDmt", "CmDmtService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmDmt?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMDMTSERVICE_WSDL_LOCATION = url;
        CMDMTSERVICE_EXCEPTION = e;
    }

    public CmDmtService() {
        super(__getWsdlLocation(), CMDMTSERVICE_QNAME);
    }

    public CmDmtService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMDMTSERVICE_QNAME, features);
    }

    public CmDmtService(URL wsdlLocation) {
        super(wsdlLocation, CMDMTSERVICE_QNAME);
    }

    public CmDmtService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMDMTSERVICE_QNAME, features);
    }

    public CmDmtService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmDmtService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CmDmtPortType
     */
    @WebEndpoint(name = "CmDmtPort")
    public CmDmtPortType getCmDmtPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmDmt", "CmDmtPort"), CmDmtPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmDmtPortType
     */
    @WebEndpoint(name = "CmDmtPort")
    public CmDmtPortType getCmDmtPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmDmt", "CmDmtPort"), CmDmtPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMDMTSERVICE_EXCEPTION!= null) {
            throw CMDMTSERVICE_EXCEPTION;
        }
        return CMDMTSERVICE_WSDL_LOCATION;
    }

}
