
package com.secusociale.portail.service.soap.listPaiements;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CM_GET_PAYMENTPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PAYMENT")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGETPAYMENTPortType {


    /**
     * 
     * @param body
     * @throws CMGETPAYMENTFault
     */
    @WebMethod(operationName = "CM_GET_PAYMENT", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PAYMENT")
    public void cmGETPAYMENT(
        @WebParam(name = "CM_GET_PAYMENT", targetNamespace = "http://oracle.com/CM_GET_PAYMENT.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CMGETPAYMENT> body)
        throws CMGETPAYMENTFault
    ;

}
