
package com.secusociale.portail.service.soap.listPaiements;

import com.secusociale.portail.config.Constants;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CM_GET_PAYMENT version 2: Liste des paiements
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CM_GET_PAYMENTService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PAYMENT", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_PAYMENT?wsdl")
public class CMGETPAYMENTService
    extends Service
{

    private final static URL CMGETPAYMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETPAYMENTSERVICE_EXCEPTION;
    private final static QName CMGETPAYMENTSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PAYMENT", "CM_GET_PAYMENTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_PAYMENT?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETPAYMENTSERVICE_WSDL_LOCATION = url;
        CMGETPAYMENTSERVICE_EXCEPTION = e;
    }

    public CMGETPAYMENTService() {
        super(__getWsdlLocation(), CMGETPAYMENTSERVICE_QNAME);
    }

    public CMGETPAYMENTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETPAYMENTSERVICE_QNAME, features);
    }

    public CMGETPAYMENTService(URL wsdlLocation) {
        super(wsdlLocation, CMGETPAYMENTSERVICE_QNAME);
    }

    public CMGETPAYMENTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETPAYMENTSERVICE_QNAME, features);
    }

    public CMGETPAYMENTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETPAYMENTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CMGETPAYMENTPortType
     */
    @WebEndpoint(name = "CM_GET_PAYMENTPort")
    public CMGETPAYMENTPortType getCMGETPAYMENTPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PAYMENT", "CM_GET_PAYMENTPort"), CMGETPAYMENTPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGETPAYMENTPortType
     */
    @WebEndpoint(name = "CM_GET_PAYMENTPort")
    public CMGETPAYMENTPortType getCMGETPAYMENTPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PAYMENT", "CM_GET_PAYMENTPort"), CMGETPAYMENTPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETPAYMENTSERVICE_EXCEPTION!= null) {
            throw CMGETPAYMENTSERVICE_EXCEPTION;
        }
        return CMGETPAYMENTSERVICE_WSDL_LOCATION;
    }

}
