
package com.secusociale.portail.service.soap.infosEmployeur;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "CM_INFOS_EMPLOYEURPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFOS_EMPLOYEUR")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMINFOSEMPLOYEURPortType {


    /**
     *
     * @param body
     * @throws CMINFOSEMPLOYEURFault
     */
    @WebMethod(operationName = "CM_INFOS_EMPLOYEUR", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFOS_EMPLOYEUR")
    public void cmINFOSEMPLOYEUR(
        @WebParam(name = "CM_INFOS_EMPLOYEUR", targetNamespace = "http://oracle.com/CM_INFOS_EMPLOYEUR.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CMINFOSEMPLOYEUR> body)
        throws Exception
    ;

}
