
package com.secusociale.portail.service.soap.succursales;

import com.secusociale.portail.config.Constants;
import com.secusociale.portail.service.PortailConstant;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM_GET_LISTE_SECURSALES version 2: Recuperation de la liste des secursales
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CM_GET_LISTE_SECURSALESService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_LISTE_SECURSALES", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_LISTE_SECURSALES?wsdl")
public class CMGETLISTESECURSALESService
    extends Service
{

    private final static URL CMGETLISTESECURSALESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETLISTESECURSALESSERVICE_EXCEPTION;
    private final static QName CMGETLISTESECURSALESSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_LISTE_SECURSALES", "CM_GET_LISTE_SECURSALESService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.CM_GET_LISTE_SECURSALES_REG_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETLISTESECURSALESSERVICE_WSDL_LOCATION = url;
        CMGETLISTESECURSALESSERVICE_EXCEPTION = e;
    }

    public CMGETLISTESECURSALESService() {
        super(__getWsdlLocation(), CMGETLISTESECURSALESSERVICE_QNAME);
    }

    public CMGETLISTESECURSALESService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETLISTESECURSALESSERVICE_QNAME, features);
    }

    public CMGETLISTESECURSALESService(URL wsdlLocation) {
        super(wsdlLocation, CMGETLISTESECURSALESSERVICE_QNAME);
    }

    public CMGETLISTESECURSALESService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETLISTESECURSALESSERVICE_QNAME, features);
    }

    public CMGETLISTESECURSALESService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETLISTESECURSALESService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CMGETLISTESECURSALESPortType
     */
    @WebEndpoint(name = "CM_GET_LISTE_SECURSALESPort")
    public CMGETLISTESECURSALESPortType getCMGETLISTESECURSALESPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_LISTE_SECURSALES", "CM_GET_LISTE_SECURSALESPort"), CMGETLISTESECURSALESPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGETLISTESECURSALESPortType
     */
    @WebEndpoint(name = "CM_GET_LISTE_SECURSALESPort")
    public CMGETLISTESECURSALESPortType getCMGETLISTESECURSALESPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_LISTE_SECURSALES", "CM_GET_LISTE_SECURSALESPort"), CMGETLISTESECURSALESPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETLISTESECURSALESSERVICE_EXCEPTION!= null) {
            throw CMGETLISTESECURSALESSERVICE_EXCEPTION;
        }
        return CMGETLISTESECURSALESSERVICE_WSDL_LOCATION;
    }

}
