
package com.secusociale.portail.service.soap.succursales;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CM_GET_LISTE_SECURSALESPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_LISTE_SECURSALES")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGETLISTESECURSALESPortType {


    /**
     * 
     * @param body
     * @throws CMGETLISTESECURSALESFault
     */
    @WebMethod(operationName = "CM_GET_LISTE_SECURSALES", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_LISTE_SECURSALES")
    public void cmGETLISTESECURSALES(
        @WebParam(name = "CM_GET_LISTE_SECURSALES", targetNamespace = "http://oracle.com/CM_GET_LISTE_SECURSALES.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CMGETLISTESECURSALES> body)
        throws CMGETLISTESECURSALESFault
    ;

}
