
package com.secusociale.portail.service.soap.urlAttestationReguralite;

import com.secusociale.portail.service.PortailConstant;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM_GEN_ATTESTATION version 2: Generation de l'attestation de regularite
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CM_GEN_ATTESTATIONService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GEN_ATTESTATION", wsdlLocation = PortailConstant.GEN_ATTESTATION_REG_WSDL)
public class CMGENATTESTATIONService
    extends Service
{

    private final static URL CMGENATTESTATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGENATTESTATIONSERVICE_EXCEPTION;
    private final static QName CMGENATTESTATIONSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GEN_ATTESTATION", "CM_GEN_ATTESTATIONService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.GEN_ATTESTATION_REG_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGENATTESTATIONSERVICE_WSDL_LOCATION = url;
        CMGENATTESTATIONSERVICE_EXCEPTION = e;
    }

    public CMGENATTESTATIONService() {
        super(__getWsdlLocation(), CMGENATTESTATIONSERVICE_QNAME);
    }

    public CMGENATTESTATIONService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGENATTESTATIONSERVICE_QNAME, features);
    }

    public CMGENATTESTATIONService(URL wsdlLocation) {
        super(wsdlLocation, CMGENATTESTATIONSERVICE_QNAME);
    }

    public CMGENATTESTATIONService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGENATTESTATIONSERVICE_QNAME, features);
    }

    public CMGENATTESTATIONService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGENATTESTATIONService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CMGENATTESTATIONPortType
     */
    @WebEndpoint(name = "CM_GEN_ATTESTATIONPort")
    public CMGENATTESTATIONPortType getCMGENATTESTATIONPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GEN_ATTESTATION", "CM_GEN_ATTESTATIONPort"), CMGENATTESTATIONPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGENATTESTATIONPortType
     */
    @WebEndpoint(name = "CM_GEN_ATTESTATIONPort")
    public CMGENATTESTATIONPortType getCMGENATTESTATIONPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GEN_ATTESTATION", "CM_GEN_ATTESTATIONPort"), CMGENATTESTATIONPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGENATTESTATIONSERVICE_EXCEPTION!= null) {
            throw CMGENATTESTATIONSERVICE_EXCEPTION;
        }
        return CMGENATTESTATIONSERVICE_WSDL_LOCATION;
    }

}
