
package com.secusociale.portail.service.soap.soldeEmployeur;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "XAI_GETSOLDEPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/XAI_GETSOLDE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface XAIGETSOLDEPortType {


    /**
     *
     * @param body
     * @throws XAIGETSOLDEFault
     */
    @WebMethod(operationName = "XAI_GETSOLDE", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/XAI_GETSOLDE")
    public void xaiGETSOLDE(
        @WebParam(name = "XAI_GETSOLDE", targetNamespace = "http://oracle.com/XAI_GETSOLDE.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<XAIGETSOLDE> body)
    throws XAIGETSOLDEFault
    ;

}
