
package com.secusociale.portail.service.soap.derniersPaiements;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "DERN_PAY_EMPLOYEUR_SERVICEPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_PAY_EMPLOYEUR_SERVICE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DERNPAYEMPLOYEURSERVICEPortType {


    /**
     *
     * @param body
     * @throws DERNPAYEMPLOYEURSERVICEFault
     */
    @WebMethod(operationName = "DERN_PAY_EMPLOYEUR_SERVICE", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/DERN_PAY_EMPLOYEUR_SERVICE")
    public void dernPAYEMPLOYEURSERVICE(
        @WebParam(name = "DERN_PAY_EMPLOYEUR_SERVICE", targetNamespace = "http://oracle.com/DERN_PAY_EMPLOYEUR_SERVICE.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<DERNPAYEMPLOYEURSERVICE> body)
    throws DERNPAYEMPLOYEURSERVICEFault
    ;

}
