
package com.secusociale.portail.service.soap.infosSalaries;

import com.secusociale.portail.service.PortailConstant;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM_GET_PERSONS_LINK_TO_EMPLOYER version 2: Get Related Person
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CM_GET_PERSONS_LINK_TO_EMPLOYERService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PERSONS_LINK_TO_EMPLOYER", wsdlLocation = PortailConstant.INFOS_SALARIES_WSDL)
public class CMGETPERSONSLINKTOEMPLOYERService
    extends Service
{

    private final static URL CMGETPERSONSLINKTOEMPLOYERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETPERSONSLINKTOEMPLOYERSERVICE_EXCEPTION;
    private final static QName CMGETPERSONSLINKTOEMPLOYERSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PERSONS_LINK_TO_EMPLOYER", "CM_GET_PERSONS_LINK_TO_EMPLOYERService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(PortailConstant.INFOS_SALARIES_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETPERSONSLINKTOEMPLOYERSERVICE_WSDL_LOCATION = url;
        CMGETPERSONSLINKTOEMPLOYERSERVICE_EXCEPTION = e;
    }

    public CMGETPERSONSLINKTOEMPLOYERService() {
        super(__getWsdlLocation(), CMGETPERSONSLINKTOEMPLOYERSERVICE_QNAME);
    }

    public CMGETPERSONSLINKTOEMPLOYERService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETPERSONSLINKTOEMPLOYERSERVICE_QNAME, features);
    }

    public CMGETPERSONSLINKTOEMPLOYERService(URL wsdlLocation) {
        super(wsdlLocation, CMGETPERSONSLINKTOEMPLOYERSERVICE_QNAME);
    }

    public CMGETPERSONSLINKTOEMPLOYERService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETPERSONSLINKTOEMPLOYERSERVICE_QNAME, features);
    }

    public CMGETPERSONSLINKTOEMPLOYERService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETPERSONSLINKTOEMPLOYERService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CMGETPERSONSLINKTOEMPLOYERPortType
     */
    @WebEndpoint(name = "CM_GET_PERSONS_LINK_TO_EMPLOYERPort")
    public CMGETPERSONSLINKTOEMPLOYERPortType getCMGETPERSONSLINKTOEMPLOYERPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PERSONS_LINK_TO_EMPLOYER", "CM_GET_PERSONS_LINK_TO_EMPLOYERPort"), CMGETPERSONSLINKTOEMPLOYERPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMGETPERSONSLINKTOEMPLOYERPortType
     */
    @WebEndpoint(name = "CM_GET_PERSONS_LINK_TO_EMPLOYERPort")
    public CMGETPERSONSLINKTOEMPLOYERPortType getCMGETPERSONSLINKTOEMPLOYERPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_PERSONS_LINK_TO_EMPLOYER", "CM_GET_PERSONS_LINK_TO_EMPLOYERPort"), CMGETPERSONSLINKTOEMPLOYERPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETPERSONSLINKTOEMPLOYERSERVICE_EXCEPTION!= null) {
            throw CMGETPERSONSLINKTOEMPLOYERSERVICE_EXCEPTION;
        }
        return CMGETPERSONSLINKTOEMPLOYERSERVICE_WSDL_LOCATION;
    }

}
