
package com.secusociale.portail.service.soap.getFacture;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CM_GET_FACTUREPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_FACTURE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGETFACTUREPortType {


    /**
     * 
     * @param body
     * @throws CMGETFACTUREFault
     */
    @WebMethod(operationName = "CM_GET_FACTURE", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_FACTURE")
    public void cmGETFACTURE(
        @WebParam(name = "CM_GET_FACTURE", targetNamespace = "http://oracle.com/CM_GET_FACTURE.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CMGETFACTURE> body)
        throws CMGETFACTUREFault
    ;

}
