
package com.secusociale.portail.service.soap.recuPaiement;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * cmGenererUrlRecuEmployeur version 2: Generate Url Re?u Employeur
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "cmGenererUrlRecuEmployeurService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/cmGenererUrlRecuEmployeur", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/cmGenererUrlRecuEmployeur?wsdl")
public class CmGenererUrlRecuEmployeurService
    extends Service {

    private final static URL CMGENERERURLRECUEMPLOYEURSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGENERERURLRECUEMPLOYEURSERVICE_EXCEPTION;
    private final static QName CMGENERERURLRECUEMPLOYEURSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/cmGenererUrlRecuEmployeur", "cmGenererUrlRecuEmployeurService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/cmGenererUrlRecuEmployeur?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGENERERURLRECUEMPLOYEURSERVICE_WSDL_LOCATION = url;
        CMGENERERURLRECUEMPLOYEURSERVICE_EXCEPTION = e;
    }

    public CmGenererUrlRecuEmployeurService() {
        super(__getWsdlLocation(), CMGENERERURLRECUEMPLOYEURSERVICE_QNAME);
    }

    public CmGenererUrlRecuEmployeurService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGENERERURLRECUEMPLOYEURSERVICE_QNAME, features);
    }

    public CmGenererUrlRecuEmployeurService(URL wsdlLocation) {
        super(wsdlLocation, CMGENERERURLRECUEMPLOYEURSERVICE_QNAME);
    }

    public CmGenererUrlRecuEmployeurService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGENERERURLRECUEMPLOYEURSERVICE_QNAME, features);
    }

    public CmGenererUrlRecuEmployeurService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmGenererUrlRecuEmployeurService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * @return returns CmGenererUrlRecuEmployeurPortType
     */
    @WebEndpoint(name = "cmGenererUrlRecuEmployeurPort")
    public CmGenererUrlRecuEmployeurPortType getCmGenererUrlRecuEmployeurPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/cmGenererUrlRecuEmployeur", "cmGenererUrlRecuEmployeurPort"), CmGenererUrlRecuEmployeurPortType.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CmGenererUrlRecuEmployeurPortType
     */
    @WebEndpoint(name = "cmGenererUrlRecuEmployeurPort")
    public CmGenererUrlRecuEmployeurPortType getCmGenererUrlRecuEmployeurPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/cmGenererUrlRecuEmployeur", "cmGenererUrlRecuEmployeurPort"), CmGenererUrlRecuEmployeurPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGENERERURLRECUEMPLOYEURSERVICE_EXCEPTION != null) {
            throw CMGENERERURLRECUEMPLOYEURSERVICE_EXCEPTION;
        }
        return CMGENERERURLRECUEMPLOYEURSERVICE_WSDL_LOCATION;
    }

}
