
package com.secusociale.portail.service.soap.recuPaiement;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "cmGenererUrlRecuEmployeurPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/cmGenererUrlRecuEmployeur")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CmGenererUrlRecuEmployeurPortType {


    /**
     * 
     * @param body
     * @throws CmGenererUrlRecuEmployeurFault
     */
    @WebMethod(action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/cmGenererUrlRecuEmployeur")
    public void cmGenererUrlRecuEmployeur(
        @WebParam(name = "cmGenererUrlRecuEmployeur", targetNamespace = "http://oracle.com/cmGenererUrlRecuEmployeur.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CmGenererUrlRecuEmployeur> body)
        throws CmGenererUrlRecuEmployeurFault
    ;

}
