
package com.secusociale.portail.service.soap.preDNS;

import com.secusociale.portail.config.Constants;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CmPresDns version 2: CmPresDns
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CmPresDnsService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmPresDns", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmPresDns?WSDL")
public class CmPresDnsService
    extends Service
{

    private final static URL CMPRESDNSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMPRESDNSSERVICE_EXCEPTION;
    private final static QName CMPRESDNSSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmPresDns", "CmPresDnsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmPresDns?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMPRESDNSSERVICE_WSDL_LOCATION = url;
        CMPRESDNSSERVICE_EXCEPTION = e;
    }

    public CmPresDnsService() {
        super(__getWsdlLocation(), CMPRESDNSSERVICE_QNAME);
    }

    public CmPresDnsService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMPRESDNSSERVICE_QNAME, features);
    }

    public CmPresDnsService(URL wsdlLocation) {
        super(wsdlLocation, CMPRESDNSSERVICE_QNAME);
    }

    public CmPresDnsService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMPRESDNSSERVICE_QNAME, features);
    }

    public CmPresDnsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmPresDnsService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CmPresDnsPortType
     */
    @WebEndpoint(name = "CmPresDnsPort")
    public CmPresDnsPortType getCmPresDnsPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmPresDns", "CmPresDnsPort"), CmPresDnsPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmPresDnsPortType
     */
    @WebEndpoint(name = "CmPresDnsPort")
    public CmPresDnsPortType getCmPresDnsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmPresDns", "CmPresDnsPort"), CmPresDnsPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMPRESDNSSERVICE_EXCEPTION!= null) {
            throw CMPRESDNSSERVICE_EXCEPTION;
        }
        return CMPRESDNSSERVICE_WSDL_LOCATION;
    }

}
