
package com.secusociale.portail.service.soap.reprise_activite;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CM-AddProcessRepriseActivitePortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-AddProcessRepriseActivite")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMAddProcessRepriseActivitePortType {

    @WebMethod(operationName = "CM-AddProcessRepriseActivite", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-AddProcessRepriseActivite")
    void cmAddProcessRepriseActivite(
        @WebParam(name = "CM-AddProcessRepriseActivite", targetNamespace = "http://oracle.com/CM-AddProcessRepriseActivite.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CMAddProcessRepriseActivite> body)
        throws CMAddProcessRepriseActiviteFault
        ;

}
