
package com.secusociale.portail.service.soap.domestique;

import com.secusociale.portail.service.PortailConstant;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * inboundDomFrm version 4: inbound domfrm
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "inboundDomFrmService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/inboundDomFrm", wsdlLocation =  PortailConstant.DOMESTIQUE_WSDL)
public class InboundDomFrmService
    extends Service
{

    private final static URL INBOUNDDOMFRMSERVICE_WSDL_LOCATION;
    private final static WebServiceException INBOUNDDOMFRMSERVICE_EXCEPTION;
    private final static QName INBOUNDDOMFRMSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/inboundDomFrm", "inboundDomFrmService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL( PortailConstant.DOMESTIQUE_WSDL);
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INBOUNDDOMFRMSERVICE_WSDL_LOCATION = url;
        INBOUNDDOMFRMSERVICE_EXCEPTION = e;
    }

    public InboundDomFrmService() {
        super(__getWsdlLocation(), INBOUNDDOMFRMSERVICE_QNAME);
    }

    public InboundDomFrmService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INBOUNDDOMFRMSERVICE_QNAME, features);
    }

    public InboundDomFrmService(URL wsdlLocation) {
        super(wsdlLocation, INBOUNDDOMFRMSERVICE_QNAME);
    }

    public InboundDomFrmService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INBOUNDDOMFRMSERVICE_QNAME, features);
    }

    public InboundDomFrmService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InboundDomFrmService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns InboundDomFrmPortType
     */
    @WebEndpoint(name = "inboundDomFrmPort")
    public InboundDomFrmPortType getInboundDomFrmPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/inboundDomFrm", "inboundDomFrmPort"), InboundDomFrmPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InboundDomFrmPortType
     */
    @WebEndpoint(name = "inboundDomFrmPort")
    public InboundDomFrmPortType getInboundDomFrmPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/inboundDomFrm", "inboundDomFrmPort"), InboundDomFrmPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INBOUNDDOMFRMSERVICE_EXCEPTION!= null) {
            throw INBOUNDDOMFRMSERVICE_EXCEPTION;
        }
        return INBOUNDDOMFRMSERVICE_WSDL_LOCATION;
    }

}
