
package com.secusociale.portail.service.soap.domestique;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "inboundDomFrmPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/inboundDomFrm")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InboundDomFrmPortType {


    /**
     * 
     * @param body
     * @throws InboundDomFrmFault
     */
    @WebMethod(action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/inboundDomFrm")
    public void inboundDomFrm(
        @WebParam(name = "inboundDomFrm", targetNamespace = "http://oracle.com/inboundDomFrm.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<InboundDomFrm> body)
        throws InboundDomFrmFault
    ;

}
