
package com.secusociale.portail.service.soap.facturesDns;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM-PAYDNSXAI version 2: CM-PAYDNSXAI
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM-PAYDNSXAIService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PAYDNSXAI", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-PAYDNSXAI?WSDL")
public class CMPAYDNSXAIService
    extends Service {

    private final static URL CMPAYDNSXAISERVICE_WSDL_LOCATION;
    private final static WebServiceException CMPAYDNSXAISERVICE_EXCEPTION;
    private final static QName CMPAYDNSXAISERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PAYDNSXAI", "CM-PAYDNSXAIService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-PAYDNSXAI?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMPAYDNSXAISERVICE_WSDL_LOCATION = url;
        CMPAYDNSXAISERVICE_EXCEPTION = e;
    }

    public CMPAYDNSXAIService() {
        super(__getWsdlLocation(), CMPAYDNSXAISERVICE_QNAME);
    }

    public CMPAYDNSXAIService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMPAYDNSXAISERVICE_QNAME, features);
    }

    public CMPAYDNSXAIService(URL wsdlLocation) {
        super(wsdlLocation, CMPAYDNSXAISERVICE_QNAME);
    }

    public CMPAYDNSXAIService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMPAYDNSXAISERVICE_QNAME, features);
    }

    public CMPAYDNSXAIService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMPAYDNSXAIService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMPAYDNSXAISERVICE_EXCEPTION != null) {
            throw CMPAYDNSXAISERVICE_EXCEPTION;
        }
        return CMPAYDNSXAISERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMPAYDNSXAIPortType
     */
    @WebEndpoint(name = "CM-PAYDNSXAIPort")
    public CMPAYDNSXAIPortType getCMPAYDNSXAIPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PAYDNSXAI", "CM-PAYDNSXAIPort"), CMPAYDNSXAIPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMPAYDNSXAIPortType
     */
    @WebEndpoint(name = "CM-PAYDNSXAIPort")
    public CMPAYDNSXAIPortType getCMPAYDNSXAIPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PAYDNSXAI", "CM-PAYDNSXAIPort"), CMPAYDNSXAIPortType.class, features);
    }

}
