
package com.secusociale.portail.service.soap.facturesDns;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CM-PAYDNSXAIPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PAYDNSXAI")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMPAYDNSXAIPortType {


    /**
     * @param body
     * @throws CMPAYDNSXAIFault
     */
    @WebMethod(operationName = "CM-PAYDNSXAI", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-PAYDNSXAI")
    public void cmPAYDNSXAI(
        @WebParam(name = "CM-PAYDNSXAI", targetNamespace = "http://oracle.com/CM-PAYDNSXAI.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CMPAYDNSXAI> body)
        throws CMPAYDNSXAIFault
    ;

}
