
package com.secusociale.portail.service.soap.listeEmployes;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * EMPLOYES_LIST_SERVICE version 2: Liste des employés en cours
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "EMPLOYES_LIST_SERVICEService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/EMPLOYES_LIST_SERVICE", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/EMPLOYES_LIST_SERVICE?WSDL")
public class EMPLOYESLISTSERVICEService
    extends Service {

    private final static URL EMPLOYESLISTSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException EMPLOYESLISTSERVICESERVICE_EXCEPTION;
    private final static QName EMPLOYESLISTSERVICESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/EMPLOYES_LIST_SERVICE", "EMPLOYES_LIST_SERVICEService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/EMPLOYES_LIST_SERVICE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EMPLOYESLISTSERVICESERVICE_WSDL_LOCATION = url;
        EMPLOYESLISTSERVICESERVICE_EXCEPTION = e;
    }

    public EMPLOYESLISTSERVICEService() {
        super(__getWsdlLocation(), EMPLOYESLISTSERVICESERVICE_QNAME);
    }

    public EMPLOYESLISTSERVICEService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EMPLOYESLISTSERVICESERVICE_QNAME, features);
    }

    public EMPLOYESLISTSERVICEService(URL wsdlLocation) {
        super(wsdlLocation, EMPLOYESLISTSERVICESERVICE_QNAME);
    }

    public EMPLOYESLISTSERVICEService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EMPLOYESLISTSERVICESERVICE_QNAME, features);
    }

    public EMPLOYESLISTSERVICEService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EMPLOYESLISTSERVICEService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (EMPLOYESLISTSERVICESERVICE_EXCEPTION != null) {
            throw EMPLOYESLISTSERVICESERVICE_EXCEPTION;
        }
        return EMPLOYESLISTSERVICESERVICE_WSDL_LOCATION;
    }

    /**
     *
     * @return
     *     returns EMPLOYESLISTSERVICEPortType
     */
    @WebEndpoint(name = "EMPLOYES_LIST_SERVICEPort")
    public EMPLOYESLISTSERVICEPortType getEMPLOYESLISTSERVICEPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/EMPLOYES_LIST_SERVICE", "EMPLOYES_LIST_SERVICEPort"), EMPLOYESLISTSERVICEPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EMPLOYESLISTSERVICEPortType
     */
    @WebEndpoint(name = "EMPLOYES_LIST_SERVICEPort")
    public EMPLOYESLISTSERVICEPortType getEMPLOYESLISTSERVICEPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/EMPLOYES_LIST_SERVICE", "EMPLOYES_LIST_SERVICEPort"), EMPLOYESLISTSERVICEPortType.class, features);
    }

}
