
package com.secusociale.portail.service.soap.listeEmployes;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "EMPLOYES_LIST_SERVICEPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/EMPLOYES_LIST_SERVICE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EMPLOYESLISTSERVICEPortType {


    /**
     *
     * @param body
     * @throws EMPLOYESLISTSERVICEFault
     */
    @WebMethod(operationName = "EMPLOYES_LIST_SERVICE", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/EMPLOYES_LIST_SERVICE")
    public void employesLISTSERVICE(
        @WebParam(name = "EMPLOYES_LIST_SERVICE", targetNamespace = "http://oracle.com/EMPLOYES_LIST_SERVICE.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<EMPLOYESLISTSERVICE> body)
    throws Exception
    ;

}
