
package com.secusociale.portail.service.soap.declaration.existance.cm_has_dns;

import com.secusociale.portail.config.Constants;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CM_HAS_DNS version 2: Vérifie si l'employeur a une DNS pour une période donnée
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CM_HAS_DNSService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_HAS_DNS", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_HAS_DNS?wsdl")
public class CMHASDNSService
    extends Service
{

    private final static URL CMHASDNSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMHASDNSSERVICE_EXCEPTION;
    private final static QName CMHASDNSSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_HAS_DNS", "CM_HAS_DNSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_HAS_DNS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMHASDNSSERVICE_WSDL_LOCATION = url;
        CMHASDNSSERVICE_EXCEPTION = e;
    }

    public CMHASDNSService() {
        super(__getWsdlLocation(), CMHASDNSSERVICE_QNAME);
    }

    public CMHASDNSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMHASDNSSERVICE_QNAME, features);
    }

    public CMHASDNSService(URL wsdlLocation) {
        super(wsdlLocation, CMHASDNSSERVICE_QNAME);
    }

    public CMHASDNSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMHASDNSSERVICE_QNAME, features);
    }

    public CMHASDNSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMHASDNSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CMHASDNSPortType
     */
    @WebEndpoint(name = "CM_HAS_DNSPort")
    public CMHASDNSPortType getCMHASDNSPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_HAS_DNS", "CM_HAS_DNSPort"), CMHASDNSPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMHASDNSPortType
     */
    @WebEndpoint(name = "CM_HAS_DNSPort")
    public CMHASDNSPortType getCMHASDNSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_HAS_DNS", "CM_HAS_DNSPort"), CMHASDNSPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMHASDNSSERVICE_EXCEPTION!= null) {
            throw CMHASDNSSERVICE_EXCEPTION;
        }
        return CMHASDNSSERVICE_WSDL_LOCATION;
    }

}
