
package com.secusociale.portail.service.soap.declaration.existance.cm_has_dns;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "CM_HAS_DNSPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_HAS_DNS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMHASDNSPortType {


    /**
     *
     * @param body
     * @throws CMHASDNSFault
     */
    @WebMethod(operationName = "CM_HAS_DNS", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_HAS_DNS")
    public void cmHASDNS(
        @WebParam(name = "CM_HAS_DNS", targetNamespace = "http://oracle.com/CM_HAS_DNS.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CMHASDNS> body)
        throws CMHASDNSFault
    ;

}
