
package com.secusociale.portail.service.soap.immatPublicParapublic;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IMMAT2_INBOUNDPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMAT2_INBOUND")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IMMAT2INBOUNDPortType {


    /**
     * 
     * @param body
     * @throws IMMAT2INBOUNDFault
     */
    @WebMethod(operationName = "IMMAT2_INBOUND", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/IMMAT2_INBOUND")
    public void immat2INBOUND(
        @WebParam(name = "IMMAT2_INBOUND", targetNamespace = "http://oracle.com/IMMAT2_INBOUND.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<IMMAT2INBOUND> body)
        throws IMMAT2INBOUNDFault
    ;

}
