
package com.secusociale.portail.service.soap.CmFindEmployeurByTypeId;

import com.secusociale.portail.config.Constants;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CmFindEmployeurByTypeId version 2: Recherche employeur par type d'identifiant
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CmFindEmployeurByTypeIdService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmFindEmployeurByTypeId", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmFindEmployeurByTypeId?WSDL")
public class CmFindEmployeurByTypeIdService
    extends Service
{

    private final static URL CMFINDEMPLOYEURBYTYPEIDSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMFINDEMPLOYEURBYTYPEIDSERVICE_EXCEPTION;
    private final static QName CMFINDEMPLOYEURBYTYPEIDSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmFindEmployeurByTypeId", "CmFindEmployeurByTypeIdService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmFindEmployeurByTypeId?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMFINDEMPLOYEURBYTYPEIDSERVICE_WSDL_LOCATION = url;
        CMFINDEMPLOYEURBYTYPEIDSERVICE_EXCEPTION = e;
    }

    public CmFindEmployeurByTypeIdService() {
        super(__getWsdlLocation(), CMFINDEMPLOYEURBYTYPEIDSERVICE_QNAME);
    }

    public CmFindEmployeurByTypeIdService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMFINDEMPLOYEURBYTYPEIDSERVICE_QNAME, features);
    }

    public CmFindEmployeurByTypeIdService(URL wsdlLocation) {
        super(wsdlLocation, CMFINDEMPLOYEURBYTYPEIDSERVICE_QNAME);
    }

    public CmFindEmployeurByTypeIdService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMFINDEMPLOYEURBYTYPEIDSERVICE_QNAME, features);
    }

    public CmFindEmployeurByTypeIdService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmFindEmployeurByTypeIdService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CmFindEmployeurByTypeIdPortType
     */
    @WebEndpoint(name = "CmFindEmployeurByTypeIdPort")
    public CmFindEmployeurByTypeIdPortType getCmFindEmployeurByTypeIdPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmFindEmployeurByTypeId", "CmFindEmployeurByTypeIdPort"), CmFindEmployeurByTypeIdPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CmFindEmployeurByTypeIdPortType
     */
    @WebEndpoint(name = "CmFindEmployeurByTypeIdPort")
    public CmFindEmployeurByTypeIdPortType getCmFindEmployeurByTypeIdPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmFindEmployeurByTypeId", "CmFindEmployeurByTypeIdPort"), CmFindEmployeurByTypeIdPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMFINDEMPLOYEURBYTYPEIDSERVICE_EXCEPTION!= null) {
            throw CMFINDEMPLOYEURBYTYPEIDSERVICE_EXCEPTION;
        }
        return CMFINDEMPLOYEURBYTYPEIDSERVICE_WSDL_LOCATION;
    }

}
