
package com.secusociale.portail.service.soap.recepisseDepot;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GET_RECEPISSE_DEPOT_URLPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/GET_RECEPISSE_DEPOT_URL")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GETRECEPISSEDEPOTURLPortType {


    /**
     * 
     * @param body
     * @throws GETRECEPISSEDEPOTURLFault
     */
    @WebMethod(operationName = "GET_RECEPISSE_DEPOT_URL", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/GET_RECEPISSE_DEPOT_URL")
    public void getRECEPISSEDEPOTURL(
        @WebParam(name = "GET_RECEPISSE_DEPOT_URL", targetNamespace = "http://oracle.com/GET_RECEPISSE_DEPOT_URL.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<GETRECEPISSEDEPOTURL> body)
        throws GETRECEPISSEDEPOTURLFault
    ;

}
