
package com.secusociale.portail.service.soap.moratoire;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM_GET_INFORMATION_MORATOIRE version 2: Get information pay plan
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM_GET_INFORMATION_MORATOIREService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_INFORMATION_MORATOIRE", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_INFORMATION_MORATOIRE?WSDL")
public class CMGETINFORMATIONMORATOIREService
    extends Service {

    private final static URL CMGETINFORMATIONMORATOIRESERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETINFORMATIONMORATOIRESERVICE_EXCEPTION;
    private final static QName CMGETINFORMATIONMORATOIRESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_INFORMATION_MORATOIRE", "CM_GET_INFORMATION_MORATOIREService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_INFORMATION_MORATOIRE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETINFORMATIONMORATOIRESERVICE_WSDL_LOCATION = url;
        CMGETINFORMATIONMORATOIRESERVICE_EXCEPTION = e;
    }

    public CMGETINFORMATIONMORATOIREService() {
        super(__getWsdlLocation(), CMGETINFORMATIONMORATOIRESERVICE_QNAME);
    }

    public CMGETINFORMATIONMORATOIREService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETINFORMATIONMORATOIRESERVICE_QNAME, features);
    }

    public CMGETINFORMATIONMORATOIREService(URL wsdlLocation) {
        super(wsdlLocation, CMGETINFORMATIONMORATOIRESERVICE_QNAME);
    }

    public CMGETINFORMATIONMORATOIREService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETINFORMATIONMORATOIRESERVICE_QNAME, features);
    }

    public CMGETINFORMATIONMORATOIREService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETINFORMATIONMORATOIREService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETINFORMATIONMORATOIRESERVICE_EXCEPTION != null) {
            throw CMGETINFORMATIONMORATOIRESERVICE_EXCEPTION;
        }
        return CMGETINFORMATIONMORATOIRESERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMGETINFORMATIONMORATOIREPortType
     */
    @WebEndpoint(name = "CM_GET_INFORMATION_MORATOIREPort")
    public CMGETINFORMATIONMORATOIREPortType getCMGETINFORMATIONMORATOIREPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_INFORMATION_MORATOIRE", "CM_GET_INFORMATION_MORATOIREPort"), CMGETINFORMATIONMORATOIREPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMGETINFORMATIONMORATOIREPortType
     */
    @WebEndpoint(name = "CM_GET_INFORMATION_MORATOIREPort")
    public CMGETINFORMATIONMORATOIREPortType getCMGETINFORMATIONMORATOIREPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_INFORMATION_MORATOIRE", "CM_GET_INFORMATION_MORATOIREPort"), CMGETINFORMATIONMORATOIREPortType.class, features);
    }

}
