
package com.secusociale.portail.service.soap.moratoire;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CM_GET_INFORMATION_MORATOIREPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_INFORMATION_MORATOIRE")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGETINFORMATIONMORATOIREPortType {


    /**
     * @param body
     * @throws CMGETINFORMATIONMORATOIREFault
     */
    @WebMethod(operationName = "CM_GET_INFORMATION_MORATOIRE", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_INFORMATION_MORATOIRE")
    public void cmGETINFORMATIONMORATOIRE(
        @WebParam(name = "CM_GET_INFORMATION_MORATOIRE", targetNamespace = "http://oracle.com/CM_GET_INFORMATION_MORATOIRE.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CMGETINFORMATIONMORATOIRE> body)
        throws CMGETINFORMATIONMORATOIREFault
    ;

}
