
package com.secusociale.portail.service.soap.facturesImpayes;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebFault(name = "Fault", targetNamespace = "http://ouaf.oracle.com/")
public class FACTURESIMPAYEESSERVICEFault
    extends Exception {


    private Fault faultInfo;


    public FACTURESIMPAYEESSERVICEFault(String message, Fault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }


    public FACTURESIMPAYEESSERVICEFault(String message, Fault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * @return returns fault bean: com.secusociale.portail.service.soap.facturesImpayes.Fault
     */
    public Fault getFaultInfo() {
        return faultInfo;
    }

    public void setFaultInfo(Fault faultInfo) {
        this.faultInfo = faultInfo;
    }
}
