
package com.secusociale.portail.service.soap.declarations_manquantes;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM_INFORMATION_MANQUE_DNS_IPRES version 2: Information Dns Ipres
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM_INFORMATION_MANQUE_DNS_IPRESService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFORMATION_MANQUE_DNS_IPRES", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_INFORMATION_MANQUE_DNS_IPRES?WSDL")
public class CMINFORMATIONMANQUEDNSIPRESService
    extends Service {

    private final static URL CMINFORMATIONMANQUEDNSIPRESSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMINFORMATIONMANQUEDNSIPRESSERVICE_EXCEPTION;
    private final static QName CMINFORMATIONMANQUEDNSIPRESSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFORMATION_MANQUE_DNS_IPRES", "CM_INFORMATION_MANQUE_DNS_IPRESService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_INFORMATION_MANQUE_DNS_IPRES?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMINFORMATIONMANQUEDNSIPRESSERVICE_WSDL_LOCATION = url;
        CMINFORMATIONMANQUEDNSIPRESSERVICE_EXCEPTION = e;
    }

    public CMINFORMATIONMANQUEDNSIPRESService() {
        super(__getWsdlLocation(), CMINFORMATIONMANQUEDNSIPRESSERVICE_QNAME);
    }

    public CMINFORMATIONMANQUEDNSIPRESService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMINFORMATIONMANQUEDNSIPRESSERVICE_QNAME, features);
    }

    public CMINFORMATIONMANQUEDNSIPRESService(URL wsdlLocation) {
        super(wsdlLocation, CMINFORMATIONMANQUEDNSIPRESSERVICE_QNAME);
    }

    public CMINFORMATIONMANQUEDNSIPRESService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMINFORMATIONMANQUEDNSIPRESSERVICE_QNAME, features);
    }

    public CMINFORMATIONMANQUEDNSIPRESService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMINFORMATIONMANQUEDNSIPRESService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMINFORMATIONMANQUEDNSIPRESSERVICE_EXCEPTION != null) {
            throw CMINFORMATIONMANQUEDNSIPRESSERVICE_EXCEPTION;
        }
        return CMINFORMATIONMANQUEDNSIPRESSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMINFORMATIONMANQUEDNSIPRESPortType
     */
    @WebEndpoint(name = "CM_INFORMATION_MANQUE_DNS_IPRESPort")
    public CMINFORMATIONMANQUEDNSIPRESPortType getCMINFORMATIONMANQUEDNSIPRESPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFORMATION_MANQUE_DNS_IPRES", "CM_INFORMATION_MANQUE_DNS_IPRESPort"), CMINFORMATIONMANQUEDNSIPRESPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMINFORMATIONMANQUEDNSIPRESPortType
     */
    @WebEndpoint(name = "CM_INFORMATION_MANQUE_DNS_IPRESPort")
    public CMINFORMATIONMANQUEDNSIPRESPortType getCMINFORMATIONMANQUEDNSIPRESPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_INFORMATION_MANQUE_DNS_IPRES", "CM_INFORMATION_MANQUE_DNS_IPRESPort"), CMINFORMATIONMANQUEDNSIPRESPortType.class, features);
    }

}
