
package com.secusociale.portail.service.soap.salaries.cm_per_exist;

import com.secusociale.portail.config.Constants;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * CM_PER_EXIST version 2: Vérifie si la personne exist
 *
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebServiceClient(name = "CM_PER_EXISTService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_PER_EXIST", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_PER_EXIST?WSDL")
public class CMPEREXISTService
    extends Service
{

    private final static URL CMPEREXISTSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMPEREXISTSERVICE_EXCEPTION;
    private final static QName CMPEREXISTSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_PER_EXIST", "CM_PER_EXISTService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_PER_EXIST?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMPEREXISTSERVICE_WSDL_LOCATION = url;
        CMPEREXISTSERVICE_EXCEPTION = e;
    }

    public CMPEREXISTService() {
        super(__getWsdlLocation(), CMPEREXISTSERVICE_QNAME);
    }

    public CMPEREXISTService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMPEREXISTSERVICE_QNAME, features);
    }

    public CMPEREXISTService(URL wsdlLocation) {
        super(wsdlLocation, CMPEREXISTSERVICE_QNAME);
    }

    public CMPEREXISTService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMPEREXISTSERVICE_QNAME, features);
    }

    public CMPEREXISTService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMPEREXISTService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CMPEREXISTPortType
     */
    @WebEndpoint(name = "CM_PER_EXISTPort")
    public CMPEREXISTPortType getCMPEREXISTPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_PER_EXIST", "CM_PER_EXISTPort"), CMPEREXISTPortType.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CMPEREXISTPortType
     */
    @WebEndpoint(name = "CM_PER_EXISTPort")
    public CMPEREXISTPortType getCMPEREXISTPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_PER_EXIST", "CM_PER_EXISTPort"), CMPEREXISTPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CMPEREXISTSERVICE_EXCEPTION!= null) {
            throw CMPEREXISTSERVICE_EXCEPTION;
        }
        return CMPEREXISTSERVICE_WSDL_LOCATION;
    }

}
