
package com.secusociale.portail.service.soap.salaries.cm_per_exist;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CM_PER_EXISTPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_PER_EXIST")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMPEREXISTPortType {


    /**
     * 
     * @param body
     * @throws CMPEREXISTFault
     */
    @WebMethod(operationName = "CM_PER_EXIST", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_PER_EXIST")
    public void cmPEREXIST(
        @WebParam(name = "CM_PER_EXIST", targetNamespace = "http://oracle.com/CM_PER_EXIST.xsd", mode = WebParam.Mode.INOUT, partName = "body")
        Holder<CMPEREXIST> body)
        throws CMPEREXISTFault
    ;

}
