
package com.secusociale.portail.service.soap.url_reception_cessation_suspension;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CM-GetUrlAccuseReceptionCessationAndSuspensionPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionCessationAndSuspension")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGetUrlAccuseReceptionCessationAndSuspensionPortType {


    /**
     * @param body
     * @throws CMGetUrlAccuseReceptionCessationAndSuspensionFault
     */
    @WebMethod(operationName = "CM-GetUrlAccuseReceptionCessationAndSuspension", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionCessationAndSuspension")
    public void cmGetUrlAccuseReceptionCessationAndSuspension(
        @WebParam(name = "CM-GetUrlAccuseReceptionCessationAndSuspension", targetNamespace = "http://oracle.com/CM-GetUrlAccuseReceptionCessationAndSuspension.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CMGetUrlAccuseReceptionCessationAndSuspension> body)
        throws CMGetUrlAccuseReceptionCessationAndSuspensionFault
    ;

}
