
package com.secusociale.portail.service.soap.url_reception_cessation_suspension;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM-GetUrlAccuseReceptionCessationAndSuspension version 2: Description
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM-GetUrlAccuseReceptionCessationAndSuspensionService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionCessationAndSuspension", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-GetUrlAccuseReceptionCessationAndSuspension?WSDL")
public class CMGetUrlAccuseReceptionCessationAndSuspensionService
    extends Service {

    private final static URL CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_EXCEPTION;
    private final static QName CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionCessationAndSuspension", "CM-GetUrlAccuseReceptionCessationAndSuspensionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-GetUrlAccuseReceptionCessationAndSuspension?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_WSDL_LOCATION = url;
        CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_EXCEPTION = e;
    }

    public CMGetUrlAccuseReceptionCessationAndSuspensionService() {
        super(__getWsdlLocation(), CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_QNAME);
    }

    public CMGetUrlAccuseReceptionCessationAndSuspensionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_QNAME, features);
    }

    public CMGetUrlAccuseReceptionCessationAndSuspensionService(URL wsdlLocation) {
        super(wsdlLocation, CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_QNAME);
    }

    public CMGetUrlAccuseReceptionCessationAndSuspensionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_QNAME, features);
    }

    public CMGetUrlAccuseReceptionCessationAndSuspensionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGetUrlAccuseReceptionCessationAndSuspensionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_EXCEPTION != null) {
            throw CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_EXCEPTION;
        }
        return CMGETURLACCUSERECEPTIONCESSATIONANDSUSPENSIONSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMGetUrlAccuseReceptionCessationAndSuspensionPortType
     */
    @WebEndpoint(name = "CM-GetUrlAccuseReceptionCessationAndSuspensionPort")
    public CMGetUrlAccuseReceptionCessationAndSuspensionPortType getCMGetUrlAccuseReceptionCessationAndSuspensionPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionCessationAndSuspension", "CM-GetUrlAccuseReceptionCessationAndSuspensionPort"), CMGetUrlAccuseReceptionCessationAndSuspensionPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMGetUrlAccuseReceptionCessationAndSuspensionPortType
     */
    @WebEndpoint(name = "CM-GetUrlAccuseReceptionCessationAndSuspensionPort")
    public CMGetUrlAccuseReceptionCessationAndSuspensionPortType getCMGetUrlAccuseReceptionCessationAndSuspensionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetUrlAccuseReceptionCessationAndSuspension", "CM-GetUrlAccuseReceptionCessationAndSuspensionPort"), CMGetUrlAccuseReceptionCessationAndSuspensionPortType.class, features);
    }

}
