
package com.secusociale.portail.service.soap.remise_gracieuse_add;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CmAddDemandeRemiseGracieusePortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmAddDemandeRemiseGracieuse")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CmAddDemandeRemiseGracieusePortType {


    /**
     * @param body
     * @throws CmAddDemandeRemiseGracieuseFault
     */
    @WebMethod(operationName = "CmAddDemandeRemiseGracieuse", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmAddDemandeRemiseGracieuse")
    public void cmAddDemandeRemiseGracieuse(
        @WebParam(name = "CmAddDemandeRemiseGracieuse", targetNamespace = "http://oracle.com/CmAddDemandeRemiseGracieuse.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CmAddDemandeRemiseGracieuse> body)
        throws CmAddDemandeRemiseGracieuseFault
    ;

}
