
package com.secusociale.portail.service.soap.remise_gracieuse_add;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CmAddDemandeRemiseGracieuse version 2: Ajouter demande remise gracieuse
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CmAddDemandeRemiseGracieuseService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmAddDemandeRemiseGracieuse", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmAddDemandeRemiseGracieuse?WSDL")
public class CmAddDemandeRemiseGracieuseService
    extends Service {

    private final static URL CMADDDEMANDEREMISEGRACIEUSESERVICE_WSDL_LOCATION;
    private final static WebServiceException CMADDDEMANDEREMISEGRACIEUSESERVICE_EXCEPTION;
    private final static QName CMADDDEMANDEREMISEGRACIEUSESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmAddDemandeRemiseGracieuse", "CmAddDemandeRemiseGracieuseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CmAddDemandeRemiseGracieuse?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMADDDEMANDEREMISEGRACIEUSESERVICE_WSDL_LOCATION = url;
        CMADDDEMANDEREMISEGRACIEUSESERVICE_EXCEPTION = e;
    }

    public CmAddDemandeRemiseGracieuseService() {
        super(__getWsdlLocation(), CMADDDEMANDEREMISEGRACIEUSESERVICE_QNAME);
    }

    public CmAddDemandeRemiseGracieuseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMADDDEMANDEREMISEGRACIEUSESERVICE_QNAME, features);
    }

    public CmAddDemandeRemiseGracieuseService(URL wsdlLocation) {
        super(wsdlLocation, CMADDDEMANDEREMISEGRACIEUSESERVICE_QNAME);
    }

    public CmAddDemandeRemiseGracieuseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMADDDEMANDEREMISEGRACIEUSESERVICE_QNAME, features);
    }

    public CmAddDemandeRemiseGracieuseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CmAddDemandeRemiseGracieuseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMADDDEMANDEREMISEGRACIEUSESERVICE_EXCEPTION != null) {
            throw CMADDDEMANDEREMISEGRACIEUSESERVICE_EXCEPTION;
        }
        return CMADDDEMANDEREMISEGRACIEUSESERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CmAddDemandeRemiseGracieusePortType
     */
    @WebEndpoint(name = "CmAddDemandeRemiseGracieusePort")
    public CmAddDemandeRemiseGracieusePortType getCmAddDemandeRemiseGracieusePort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmAddDemandeRemiseGracieuse", "CmAddDemandeRemiseGracieusePort"), CmAddDemandeRemiseGracieusePortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CmAddDemandeRemiseGracieusePortType
     */
    @WebEndpoint(name = "CmAddDemandeRemiseGracieusePort")
    public CmAddDemandeRemiseGracieusePortType getCmAddDemandeRemiseGracieusePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CmAddDemandeRemiseGracieuse", "CmAddDemandeRemiseGracieusePort"), CmAddDemandeRemiseGracieusePortType.class, features);
    }

}
