
package com.secusociale.portail.service.soap.remise_gracieuse_statut;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CM-GetStatusRemiseGracieusePortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRemiseGracieuse")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGetStatusRemiseGracieusePortType {


    /**
     * @param body
     * @throws CMGetStatusRemiseGracieuseFault
     */
    @WebMethod(operationName = "CM-GetStatusRemiseGracieuse", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRemiseGracieuse")
    public void cmGetStatusRemiseGracieuse(
        @WebParam(name = "CM-GetStatusRemiseGracieuse", targetNamespace = "http://oracle.com/CM-GetStatusRemiseGracieuse.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CMGetStatusRemiseGracieuse> body)
        throws CMGetStatusRemiseGracieuseFault
    ;

}
