
package com.secusociale.portail.service.soap.remise_gracieuse_statut;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM-GetStatusRemiseGracieuse version 2: get status demande remise gracieuse
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM-GetStatusRemiseGracieuseService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRemiseGracieuse", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-GetStatusRemiseGracieuse?WSDL")
public class CMGetStatusRemiseGracieuseService
    extends Service {

    private final static URL CMGETSTATUSREMISEGRACIEUSESERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETSTATUSREMISEGRACIEUSESERVICE_EXCEPTION;
    private final static QName CMGETSTATUSREMISEGRACIEUSESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRemiseGracieuse", "CM-GetStatusRemiseGracieuseService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM-GetStatusRemiseGracieuse?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETSTATUSREMISEGRACIEUSESERVICE_WSDL_LOCATION = url;
        CMGETSTATUSREMISEGRACIEUSESERVICE_EXCEPTION = e;
    }

    public CMGetStatusRemiseGracieuseService() {
        super(__getWsdlLocation(), CMGETSTATUSREMISEGRACIEUSESERVICE_QNAME);
    }

    public CMGetStatusRemiseGracieuseService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETSTATUSREMISEGRACIEUSESERVICE_QNAME, features);
    }

    public CMGetStatusRemiseGracieuseService(URL wsdlLocation) {
        super(wsdlLocation, CMGETSTATUSREMISEGRACIEUSESERVICE_QNAME);
    }

    public CMGetStatusRemiseGracieuseService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETSTATUSREMISEGRACIEUSESERVICE_QNAME, features);
    }

    public CMGetStatusRemiseGracieuseService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGetStatusRemiseGracieuseService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETSTATUSREMISEGRACIEUSESERVICE_EXCEPTION != null) {
            throw CMGETSTATUSREMISEGRACIEUSESERVICE_EXCEPTION;
        }
        return CMGETSTATUSREMISEGRACIEUSESERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMGetStatusRemiseGracieusePortType
     */
    @WebEndpoint(name = "CM-GetStatusRemiseGracieusePort")
    public CMGetStatusRemiseGracieusePortType getCMGetStatusRemiseGracieusePort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRemiseGracieuse", "CM-GetStatusRemiseGracieusePort"), CMGetStatusRemiseGracieusePortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMGetStatusRemiseGracieusePortType
     */
    @WebEndpoint(name = "CM-GetStatusRemiseGracieusePort")
    public CMGetStatusRemiseGracieusePortType getCMGetStatusRemiseGracieusePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM-GetStatusRemiseGracieuse", "CM-GetStatusRemiseGracieusePort"), CMGetStatusRemiseGracieusePortType.class, features);
    }

}
