
package com.secusociale.portail.service.soap.getTauxPlafonds;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "CM_GET_CONSTANTSPortType", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_CONSTANTS")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CMGETCONSTANTSPortType {


    /**
     * @param body
     * @throws CMGETCONSTANTSFault
     */
    @WebMethod(operationName = "CM_GET_CONSTANTS", action = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_CONSTANTS")
    public void cmGETCONSTANTS(
        @WebParam(name = "CM_GET_CONSTANTS", targetNamespace = "http://oracle.com/CM_GET_CONSTANTS.xsd", mode = WebParam.Mode.INOUT, partName = "body")
            Holder<CMGETCONSTANTS> body)
        throws CMGETCONSTANTSFault
    ;

}
