
package com.secusociale.portail.service.soap.getTauxPlafonds;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM_GET_CONSTANTS version 2: Recuperation des constante taux et plafonds pour le calcul d
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM_GET_CONSTANTSService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_CONSTANTS", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_CONSTANTS?WSDL")
public class CMGETCONSTANTSService
    extends Service {

    private final static URL CMGETCONSTANTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETCONSTANTSSERVICE_EXCEPTION;
    private final static QName CMGETCONSTANTSSERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_CONSTANTS", "CM_GET_CONSTANTSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_CONSTANTS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETCONSTANTSSERVICE_WSDL_LOCATION = url;
        CMGETCONSTANTSSERVICE_EXCEPTION = e;
    }

    public CMGETCONSTANTSService() {
        super(__getWsdlLocation(), CMGETCONSTANTSSERVICE_QNAME);
    }

    public CMGETCONSTANTSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETCONSTANTSSERVICE_QNAME, features);
    }

    public CMGETCONSTANTSService(URL wsdlLocation) {
        super(wsdlLocation, CMGETCONSTANTSSERVICE_QNAME);
    }

    public CMGETCONSTANTSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETCONSTANTSSERVICE_QNAME, features);
    }

    public CMGETCONSTANTSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETCONSTANTSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETCONSTANTSSERVICE_EXCEPTION != null) {
            throw CMGETCONSTANTSSERVICE_EXCEPTION;
        }
        return CMGETCONSTANTSSERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMGETCONSTANTSPortType
     */
    @WebEndpoint(name = "CM_GET_CONSTANTSPort")
    public CMGETCONSTANTSPortType getCMGETCONSTANTSPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_CONSTANTS", "CM_GET_CONSTANTSPort"), CMGETCONSTANTSPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMGETCONSTANTSPortType
     */
    @WebEndpoint(name = "CM_GET_CONSTANTSPort")
    public CMGETCONSTANTSPortType getCMGETCONSTANTSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_CONSTANTS", "CM_GET_CONSTANTSPort"), CMGETCONSTANTSPortType.class, features);
    }

}
