
package com.secusociale.portail.service.soap.duplicata_facture_recherche;

import com.secusociale.portail.config.Constants;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * CM_GET_NUMERO_FACTURE version 3: La liste des factures par id
 * <p>
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CM_GET_NUMERO_FACTUREService", targetNamespace = "http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_NUMERO_FACTURE", wsdlLocation = Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_NUMERO_FACTURE?WSDL")
public class CMGETNUMEROFACTUREService
    extends Service {

    private final static URL CMGETNUMEROFACTURESERVICE_WSDL_LOCATION;
    private final static WebServiceException CMGETNUMEROFACTURESERVICE_EXCEPTION;
    private final static QName CMGETNUMEROFACTURESERVICE_QNAME = new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_NUMERO_FACTURE", "CM_GET_NUMERO_FACTUREService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Constants.PSRM_URL+"/ouaf/XAIApp/xaiserver/CM_GET_NUMERO_FACTURE?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CMGETNUMEROFACTURESERVICE_WSDL_LOCATION = url;
        CMGETNUMEROFACTURESERVICE_EXCEPTION = e;
    }

    public CMGETNUMEROFACTUREService() {
        super(__getWsdlLocation(), CMGETNUMEROFACTURESERVICE_QNAME);
    }

    public CMGETNUMEROFACTUREService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CMGETNUMEROFACTURESERVICE_QNAME, features);
    }

    public CMGETNUMEROFACTUREService(URL wsdlLocation) {
        super(wsdlLocation, CMGETNUMEROFACTURESERVICE_QNAME);
    }

    public CMGETNUMEROFACTUREService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CMGETNUMEROFACTURESERVICE_QNAME, features);
    }

    public CMGETNUMEROFACTUREService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CMGETNUMEROFACTUREService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CMGETNUMEROFACTURESERVICE_EXCEPTION != null) {
            throw CMGETNUMEROFACTURESERVICE_EXCEPTION;
        }
        return CMGETNUMEROFACTURESERVICE_WSDL_LOCATION;
    }

    /**
     * @return returns CMGETNUMEROFACTUREPortType
     */
    @WebEndpoint(name = "CM_GET_NUMERO_FACTUREPort")
    public CMGETNUMEROFACTUREPortType getCMGETNUMEROFACTUREPort() {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_NUMERO_FACTURE", "CM_GET_NUMERO_FACTUREPort"), CMGETNUMEROFACTUREPortType.class);
    }

    /**
     * @param features A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CMGETNUMEROFACTUREPortType
     */
    @WebEndpoint(name = "CM_GET_NUMERO_FACTUREPort")
    public CMGETNUMEROFACTUREPortType getCMGETNUMEROFACTUREPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ouaf.oracle.com/spl/XAIXapp/xaiserver/CM_GET_NUMERO_FACTURE", "CM_GET_NUMERO_FACTUREPort"), CMGETNUMEROFACTUREPortType.class, features);
    }

}
